### ISSUE TITLE
Possible errors on my end?

### ISSUE THREAD

**Issue by Altoc** [SE-Team-Two/SpeakEasy#28]
When running the server I get these:
<gevent._socket3.socket object, fd=1040, family=2, type=1, proto=0>: Invalid HTTP method: '\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03NÎ\x99wì\n'
<gevent._socket3.socket object, fd=1044, family=2, type=1, proto=0>: Invalid http version: '\x16\x03\x01\x00µ\x01\x00\x00±\x03\x03>ä\x1d\x0c\x17}¬FmlÍÎÈ\x9b3[\x873V³\x82)¼\x8f\x13°,.À\x97!\\\x00\x00\x1cêêÀ+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00\n'

And when sending messages I get these:

Traceback (most recent call last):
  File "c:\users\ian\appdata\local\programs\python\python37-32\lib\site-packages\gevent\pywsgi.py", line 661, in handle_one_request
    if not self.read_request(self.requestline):
  File "c:\users\ian\appdata\local\programs\python\python37-32\lib\site-packages\gevent\pywsgi.py", line 522, in read_request
    raise _InvalidClientRequest('Invalid http version: %r' % (raw_requestline,))
gevent.pywsgi._InvalidClientRequest: Invalid http version: '\x16\x03\x01\x00µ\x01\x00\x00±\x03\x03Z:A\x96ÛE\x06Má£ÇvÉ\x8câ»ì-]wO\x9e\x1b³\x07%\x97\x1bp\x0bÈ\x08\x00\x00\x1c\x8a\x8aÀ+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00\n'

Unsure if I have something improperly configured or if it is the code

Any insight appreciated!

**Comment by Altoc** [comment]
Adding screenshots for breadth

![screenshot 5](https://user-images.githubusercontent.com/37989193/48281690-54a7b500-e425-11e8-9be1-92e3688de408.png)
![screenshot 6](https://user-images.githubusercontent.com/37989193/48281691-54a7b500-e425-11e8-9977-ac666c978c06.png)
